In [ ]:
import numpy as np

In [ ]:
def print_obj(obj, name):
    print("%s:\n%s\n" % (name, obj))

def check_each(a, b):
    return (a == b).astype('bool')

def check_mean(a, b):
    return np.mean(a == b).astype('bool')

### Scalars, Vectors, Matrices

In [ ]:
a = np.array(1.)
b = np.array([1., 2., 3.])
c = np.array([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
print_obj(a, "a")
print_obj(b, "b")
print_obj(c, "c")

a:
1.0

b:
[1. 2. 3.]

c:
[[1. 2. 3.]
 [4. 5. 6.]]



In [ ]:
print_obj(a.ndim, "a.ndim")
print_obj(b.ndim, "b.ndim")
print_obj(c.ndim, "c.ndim")

a.ndim:
0

b.ndim:
1

c.ndim:
2



In [ ]:
print_obj(a.shape, "a.shape")
print_obj(b.shape, "b.shape")
print_obj(c.shape, "c.shape")

a.shape:
()

b.shape:
(3,)

c.shape:
(2, 3)



### Tensors (N-dimensional array)

In [ ]:
d = np.array([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])
e = np.array([[[[1., 2., 3.], [1., 2., 3.]], [[4., 5., 6.], [4., 5., 6.]]],
              [[[7., 8., 9.], [7., 8., 9.]], [[10., 11., 12.], [10., 11., 12.]]]])

In [ ]:
print_obj(d, "d")
print_obj(d.ndim, "d.ndim")
print_obj(d.shape, "d.shape")

print_obj(e, "e")
print_obj(e.ndim, "e.ndim")
print_obj(e.shape, "e.shape")

d:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]

d.ndim:
3

d.shape:
(2, 2, 3)

e:
[[[[ 1.  2.  3.]
   [ 1.  2.  3.]]

  [[ 4.  5.  6.]
   [ 4.  5.  6.]]]


 [[[ 7.  8.  9.]
   [ 7.  8.  9.]]

  [[10. 11. 12.]
   [10. 11. 12.]]]]

e.ndim:
4

e.shape:
(2, 2, 2, 3)



In [ ]:
# Quiz: What is the shape of [[[1], [2], [3]], [[4], [5], [6]]]?
f = np.array([[[1], [2], [3]], [[4], [5], [6]]])
print_obj(f.shape, "f.shape")
"""
2, 3, 1
"""

f.shape:
(2, 3, 1)



'\n2, 3, 1\n'

### Defining Numpy arrays

In [ ]:
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
a = np.zeros((2, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a = np.full((2,5), 5)
a

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
a = np.random.random((2, 3, 4))
a

array([[[0.29719409, 0.73677082, 0.37330065, 0.83363361],
        [0.87772577, 0.20471488, 0.20896484, 0.8358938 ],
        [0.27679176, 0.61978272, 0.34352378, 0.71452133]],

       [[0.86462352, 0.81833099, 0.94438681, 0.31380379],
        [0.66513645, 0.72246687, 0.03194947, 0.79856218],
        [0.48486806, 0.82555099, 0.36672596, 0.16938926]]])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(10).astype(float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a = np.arange(10).reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# Quiz: Create a 4-by-3-by-2 tensor filled with 0.0 to 23.0

# np.arange(24).astype(float).reshape((4,3,2))
# you can also change the order reshape((4,3,2)).astype(float)
np.arange(24.0).reshape((4,3,2))

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.],
        [16., 17.]],

       [[18., 19.],
        [20., 21.],
        [22., 23.]]])

### Indexing & Slicing

In [ ]:
# Indexing and slicing a vector
a = np.arange(10)
print_obj(a, "a")

print_obj(a[0], "a[0]")
print_obj(a[1], "a[1]")
print_obj(a[-1], "a[-1]")
print_obj(a[-3], "a[-3]")

print_obj(a[0:10], "a[0:10]")
print_obj(a[0:], "a[0:]")
print_obj(a[:10], "a[:10]")
print_obj(a[:], "a[:]")

print_obj(a[7:], "a[7:]")
print_obj(a[:5], "a[:5]")
print_obj(a[2:5], "a[2:5]")

# Quiz: What is a[-4:]?
print_obj(a[-4:], "a[-4:]")
# Quiz: What is a[:-8]?
print_obj(a[:-8], "a[:-8]")

print_obj(a[0:10:2], "a[0:10:2]")
print_obj(a[0:10:3], "a[0:10:3]")
print_obj(a[2:6:3], "a[2:6:3]")

print_obj(a[::-1], "a[::-1]")
print_obj(a[8:5:-1], "a[8:5:-1]")
print_obj(a[8:5], "a[8:5]")

# Quiz: Create [9, 6, 3] using a.
print_obj(a[9:2:-3], "a[9:2:-3]")
# a[-1:1:-3]

a:
[0 1 2 3 4 5 6 7 8 9]

a[0]:
0

a[1]:
1

a[-1]:
9

a[-3]:
7

a[0:10]:
[0 1 2 3 4 5 6 7 8 9]

a[0:]:
[0 1 2 3 4 5 6 7 8 9]

a[:10]:
[0 1 2 3 4 5 6 7 8 9]

a[:]:
[0 1 2 3 4 5 6 7 8 9]

a[7:]:
[7 8 9]

a[:5]:
[0 1 2 3 4]

a[2:5]:
[2 3 4]

a[-4:]:
[6 7 8 9]

a[:-8]:
[0 1]

a[0:10:2]:
[0 2 4 6 8]

a[0:10:3]:
[0 3 6 9]

a[2:6:3]:
[2 5]

a[::-1]:
[9 8 7 6 5 4 3 2 1 0]

a[8:5:-1]:
[8 7 6]

a[8:5]:
[]

a[9:2:-3]:
[9 6 3]



In [ ]:
# Indexing a matrix
a = np.arange(9).reshape((3,3))
print_obj(a, "a")
print_obj(a[0][0], "a[0][0]")
print_obj(a[0,0], "a[0,0]")
print_obj(a[1,1], "a[1,1]")

# Quiz: How to access the last row?
# print(a[2])
# a[-1], a[-1, :]
print(a[-1, :])# whole column
# (row, column)
# Quiz: How to access the second column?
print(a[:, -2])# whole row
# Quiz: How to create [8, 5] using a?
print(a[:0:-1, -1])
# a[[2, 1], [2, 2]]

a:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

a[0][0]:
0

a[0,0]:
0

a[1,1]:
4

[6 7 8]
[1 4 7]
[8 5]


In [ ]:
# Indexing and slicing a 3D tensor
a = np.arange(4*3*2).reshape((4, 3, 2))
print_obj(a, "a")
print_obj(a[2, 1, 0], "a[2, 1, 0]")

# Quiz: What would be a[0]?
print(a[0])
# Quiz: What would be a[0, 1]?
print(a[0][1])
# Quiz: Create [[0, 2, 4], [6, 8, 10]]
b = np.array([a[0, :, 0], a[1, :, 0]])
print_obj(b, "b")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

a[2, 1, 0]:
14

[[0 1]
 [2 3]
 [4 5]]
[2 3]
b:
[[ 0  2  4]
 [ 6  8 10]]



In [ ]:
# Conditional indexing
a = np.arange(3*2).reshape((3,2))
print_obj(a, "a")

idx = a % 2 == 0
print_obj(idx, "idx")
print(a[idx])

# Quiz: How would you create [3, 4, 5] using a?
idx2 = a >=3
print(idx2)
print(a[idx2])

a:
[[0 1]
 [2 3]
 [4 5]]

idx:
[[ True False]
 [ True False]
 [ True False]]

[0 2 4]
[[False False]
 [False  True]
 [ True  True]]
[3 4 5]


In [ ]:
# Taking specific elements from a vector
a = np.arange(10)
print(a)
idx = [0, 2, 3]
print_obj(a[idx], "a[idx]")
print(a[[-1,-2,-3]])

[0 1 2 3 4 5 6 7 8 9]
a[idx]:
[0 2 3]

[9 8 7]


In [ ]:
# Taking specific elements from a tensor
a = np.arange(24).reshape((6,4))
print_obj(a, "a")

print_obj(a[:,[0, 2, 3]], "a[idx]") # all the rows
print_obj(a[[0, 2, 3], :], "a[idx]")
idx = ((0,0,1,5),(1,2,0,3))
print_obj(a[idx], "tuple indexing")
idx = np.array([[0,0,1,5],[1,2,0,3]])
print_obj(a[idx], "ndarray indexing") #<-??

a:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

a[idx]:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]
 [12 14 15]
 [16 18 19]
 [20 22 23]]

a[idx]:
[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]

tuple indexing:
[ 1  2  4 23]

ndarray indexing:
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 4  5  6  7]
  [20 21 22 23]]

 [[ 4  5  6  7]
  [ 8  9 10 11]
  [ 0  1  2  3]
  [12 13 14 15]]]



In [ ]:
# Ellipsis
a = np.arange(288).reshape((2,3,2,2,4,-1))# -1 is equl to the 3
print_obj(a.shape, "a.shape")

print_obj(a[1,:,:,:,:,2], "Plain indexing")
print_obj(a[1,...,2], "Ellipsis")

a.shape:
(2, 3, 2, 2, 4, 3)

Plain indexing:
[[[[146 149 152 155]
   [158 161 164 167]]

  [[170 173 176 179]
   [182 185 188 191]]]


 [[[194 197 200 203]
   [206 209 212 215]]

  [[218 221 224 227]
   [230 233 236 239]]]


 [[[242 245 248 251]
   [254 257 260 263]]

  [[266 269 272 275]
   [278 281 284 287]]]]

Ellipsis:
[[[[146 149 152 155]
   [158 161 164 167]]

  [[170 173 176 179]
   [182 185 188 191]]]


 [[[194 197 200 203]
   [206 209 212 215]]

  [[218 221 224 227]
   [230 233 236 239]]]


 [[[242 245 248 251]
   [254 257 260 263]]

  [[266 269 272 275]
   [278 281 284 287]]]]



### Math Operations

In [ ]:
# Basic operations
a = np.arange(6).reshape((3, 2))
b = np.ones((3, 2))
print_obj(a, "a")
print_obj(b, "b")

# +, -, *, /
print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

a+b:
[[1. 2.]
 [3. 4.]
 [5. 6.]]

a-b:
[[-1.  0.]
 [ 1.  2.]
 [ 3.  4.]]

a*b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]

a/b:
[[0. 1.]
 [2. 3.]
 [4. 5.]]



In [ ]:
# Unary operations
a = np.arange(6).reshape((3,2))
print_obj(a, "a")

print_obj(a.sum(), "a.sum()")
print_obj(a.sum(axis=0), "a.sum(axis=0)")# row wise addition
print_obj(a.sum(axis=1), "a.sum(axis=1)")# column wise addition

print_obj(a.mean(), "a.mean()")
# a.mean(axis=0)
print_obj(a.max(), "a.max()")
# a.max(axis=0)
print_obj(a.min(), "a.min()")

# Quiz: Given a = np.arange(24).reshape((2,3,4)), what is the mean of the sum w.r.t to the last dimension? <-??
b = np.arange(24).reshape((2,3,4))
print_obj(b, "b")
print_obj(b.mean(axis=2), "b.mean(axis=2)")

a:
[[0 1]
 [2 3]
 [4 5]]

a.sum():
15

a.sum(axis=0):
[6 9]

a.sum(axis=1):
[1 5 9]

a.mean():
2.5

a.max():
5

a.min():
0

b:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

b.mean(axis=2):
[[ 1.5  5.5  9.5]
 [13.5 17.5 21.5]]



In [ ]:
# Vector dot product
a = np.arange(3).astype('float')
b = np.ones(3)
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a, b), "a dot b")

a:
[0. 1. 2.]

b:
[1. 1. 1.]

a dot b:
3.0



In [ ]:
# Matrix dot product, matrix multiplication
a = np.arange(6).reshape((3, 2))
b = np.ones((2, 3))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b), "a dot b")
print_obj(a@b, "a @ b")

a:
[[0 1]
 [2 3]
 [4 5]]

b:
[[1. 1. 1.]
 [1. 1. 1.]]

a dot b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]

a @ b:
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]



In [ ]:
# Tensor dot product, tensor multiplication
# a = np.arange(24).reshape((4, 3, 2))
# b = np.ones((4, 2, 3))
a = np.arange(48).reshape((4, 2, 3, 2))
b = np.ones((4, 2, 2, 3))

print_obj(a, "a")
print_obj(b, "b")

print_obj(np.dot(a,b).shape, "a dot b")

print_obj((a@b).shape, "a @ b")
# skip first 4 -> (4, 3, 3)

# usually learning process -> first element is batch element // 4 is mini batch, batch indexing

# Quiz: what would happen if a.shape==(4,3,2) and b.shape==(2,3)?
c = np.arange(24).reshape((4, 3, 2))
d = np.ones((2, 3))# broadcasting
print_obj((c@d).shape, "c@d")

a:
[[[[ 0  1]
   [ 2  3]
   [ 4  5]]

  [[ 6  7]
   [ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]
   [16 17]]

  [[18 19]
   [20 21]
   [22 23]]]


 [[[24 25]
   [26 27]
   [28 29]]

  [[30 31]
   [32 33]
   [34 35]]]


 [[[36 37]
   [38 39]
   [40 41]]

  [[42 43]
   [44 45]
   [46 47]]]]

b:
[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]

a dot b:
(4, 2, 3, 4, 2, 3)

a @ b:
(4, 2, 3, 3)

c@d:
(4, 3, 3)



### Shape Manipulation

In [ ]:
# Reshapes
a = np.arange(24).reshape((2, 3, 4))
print_obj(a, "a")

b = a.reshape((6, 4))
print_obj(b, "b")

c = a.reshape((6, -1))# -1 : machine figure out
print_obj(c, "c")

# Quiz: What would d=a.reshape((6, 4, -1)) look like?
d=a.reshape((6, 4, -1))
print_obj(d, "d")# (6,4,1)

a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

b:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

c:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

d:
[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]



In [ ]:
# Adding an extra dimension
a = np.arange(3)
print_obj(a, "a")

print_obj(a[:, None], "a[:, None]")#(3,1)

# Quiz: How to make a = np.ones((3,4)) into shape (3, 1, 1, 4) using reshape and None?
b = np.ones((3,4))
c = b[:, None, None, :]
print_obj(c, "c")

a:
[0 1 2]

a[:, None]:
[[0]
 [1]
 [2]]

c:
[[[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]


 [[[1. 1. 1. 1.]]]]



In [ ]:
# Stack, concatenation
a = np.ones((3,2))
b = np.zeros((3,2))
print_obj(a, "a")
print_obj(b, "b")

print_obj(np.vstack([a, b]), "a,b vstack") # vertical
print_obj(np.hstack([a, b]), "a,b hstack") # horizontal
print_obj(np.hstack([a, b, a]), "a,b,a hstack")

print_obj(np.concatenate([a, b], axis=0), "a,b concat axis=0") # row wise
print_obj(np.concatenate([a, b], axis=1), "a,b concat axis=1") # column wise

# Quiz: Would concatenating two tensors whose shapes are (4, 3, 2) and (5, 4, 2) on axis=2 work?
# Answer : No, remaining dim does not match (5,4,3) (5,4,2) <- so, target dim does not matter

c = np.ones((5,4,3))
d = np.zeros((5,4,2))
np.concatenate([c,d], axis=2)

a:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

b:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

a,b vstack:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b hstack:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]

a,b,a hstack:
[[1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 1.]]

a,b concat axis=0:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

a,b concat axis=1:
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]



array([[[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]],

       [[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]],

       [[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]],

       [[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]],

       [[1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 0., 0.]]])

In [ ]:
# Matrix transpose
a = np.arange(6).reshape((3, 2))
print_obj(a, "a")

print_obj(a.T, "a.T")

a:
[[0 1]
 [2 3]
 [4 5]]

a.T:
[[0 2 4]
 [1 3 5]]



In [ ]:
# Tensor transpose
# swaping btw rows and columns
a = np.arange(24).reshape((4, 3, 2))
print_obj(a, "a")

b = np.transpose(a, [0, 2, 1]) # (4, 2, 3)
print_obj(b, "Swap axis 1 and 2")
print_obj(b.shape, "b's shape")

c = np.transpose(a, [1, 0, 2]) # (3, 4, 2)
print_obj(c, "Swap axis 0 and 1")
print_obj(c.shape, "c's shape")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]

Swap axis 1 and 2:
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]

b's shape:
(4, 2, 3)

Swap axis 0 and 1:
[[[ 0  1]
  [ 6  7]
  [12 13]
  [18 19]]

 [[ 2  3]
  [ 8  9]
  [14 15]
  [20 21]]

 [[ 4  5]
  [10 11]
  [16 17]
  [22 23]]]

c's shape:
(3, 4, 2)



### Broadcasting

In [ ]:
# Vector and scalar
a = np.arange(3)
b = 2.
# b = np.array([2., 2., 2.])
print_obj(a, "a")

print_obj(a+b, "a+b")
print_obj(a-b, "a-b")
print_obj(a*b, "a*b")
print_obj(a/b, "a/b")

a:
[0 1 2]

a+b:
[2. 3. 4.]

a-b:
[-2. -1.  0.]

a*b:
[0. 2. 4.]

a/b:
[0.  0.5 1. ]



In [ ]:
# Matrix and vector
a = np.arange(6).reshape((3,2))
b = np.arange(2).reshape(2) + 1
print_obj(a, "a")
# print_obj(b, "b")

# b = np.array([[1,2],[1,2],[1,2]])

print_obj(a+b, "a+b")

# Quiz: What would happen if b were np.arange(2).reshape((2, 1))? How about np.arange(2).reshape((1, 2))?
# c = np.arange(2).reshape((2,1)) + 1
c = np.arange(2).reshape((1,2)) + 1

print_obj(c, "c")

# print_obj(a+c, "a+c") # error
print_obj(a+c, "a+c") # success for broadcasting


a:
[[0 1]
 [2 3]
 [4 5]]

a+b:
[[1 3]
 [3 5]
 [5 7]]

c:
[[1 2]]

a+c:
[[1 3]
 [3 5]
 [5 7]]



In [ ]:
# Tensor and matrix
a = np.arange(12).reshape((2,3,2))
# b = np.arange(6).reshape((3,2)) # 2
b = np.arange(2).reshape((1,2)) # 2
print_obj(a, "a")
print_obj(b, "b")

# b = np.array([[[0,1], [2,3], [4,5]], [[0,1], [2,3], [4,5]]])
# b = np.array([1,2]) <- also broadcasting also work
# last acces need to match

print_obj(a+b, "a+b")

#Quiz: How can we use None to do a+b?
c = np.arange(12).reshape((2,3,2))
d = np.arange(6).reshape((3,2))
d = d[None,:,:]
print_obj(c+d, "c+d")

a:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

b:
[[0 1]]

a+b:
[[[ 0  2]
  [ 2  4]
  [ 4  6]]

 [[ 6  8]
  [ 8 10]
  [10 12]]]

c+d:
[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[ 6  8]
  [10 12]
  [14 16]]]



### Final Quiz

In [ ]:
def sigmoid(x):
    return 1./(1. + np.exp(-x))

# Define a function that, given M of shape (m,n) and W of shape (4n, n), executes the following (assume m is an even number):
# - Take the first half rows of M
# - Take the second half rows of M
# - Take the odd-numbered rows of M
# - Take the even-numbered rows of M
# - Append them horizontally in the listed order so that you obtain a matrix X of shape (?, 4n)
# - Linearly transform X with W so that you obtain a matrix Y of shape (?, ?)
# - Put Y through the sigmoid function
# - Obtain the sum of the mean of each column
def foo(M, W):
    m = M.shape[0]
    fhrM = M[:(m//2)]
    shrM = M[(m//2):]
    list1 = np.arange(1, (m//2)+1)*2-1
    print(list1)
    onrM = M[list1].reshape(((m//2),-1))
    print(onrM)
    list2 = np.arange(0, (m//2))*2
    print(list2)
    enrM = M[list2].reshape(((m//2),-1))
    X = np.concatenate([fhrM, shrM, onrM, enrM], axis=1)
    # print(X)
    res = sigmoid(X @ W)
    res2 = res.mean(axis=0)
    res3 = np.sum(res2)

    return res3

M = (np.arange(60).reshape((20,3)).astype('float') - 10.) / 10
W = np.arange(36).reshape(12,3).astype('float') / 10.

# 2.7013292476222723
res = foo(M, W)
print(res)

"""
def foo(M, W):
    m = M.shape[0]
    X = np.hstack([M[:m//2], M[m//2:], M[1::2], M[::2]])
    Y = sigmoid(X @ W)
    return np.sum(Y.mean(axis=0))
"""

[ 1  3  5  7  9 11 13 15 17 19]
[[-0.7 -0.6 -0.5]
 [-0.1  0.   0.1]
 [ 0.5  0.6  0.7]
 [ 1.1  1.2  1.3]
 [ 1.7  1.8  1.9]
 [ 2.3  2.4  2.5]
 [ 2.9  3.   3.1]
 [ 3.5  3.6  3.7]
 [ 4.1  4.2  4.3]
 [ 4.7  4.8  4.9]]
[ 0  2  4  6  8 10 12 14 16 18]
[[-1.  -0.9 -0.8  2.   2.1  2.2 -0.7 -0.6 -0.5 -1.  -0.9 -0.8]
 [-0.7 -0.6 -0.5  2.3  2.4  2.5 -0.1  0.   0.1 -0.4 -0.3 -0.2]
 [-0.4 -0.3 -0.2  2.6  2.7  2.8  0.5  0.6  0.7  0.2  0.3  0.4]
 [-0.1  0.   0.1  2.9  3.   3.1  1.1  1.2  1.3  0.8  0.9  1. ]
 [ 0.2  0.3  0.4  3.2  3.3  3.4  1.7  1.8  1.9  1.4  1.5  1.6]
 [ 0.5  0.6  0.7  3.5  3.6  3.7  2.3  2.4  2.5  2.   2.1  2.2]
 [ 0.8  0.9  1.   3.8  3.9  4.   2.9  3.   3.1  2.6  2.7  2.8]
 [ 1.1  1.2  1.3  4.1  4.2  4.3  3.5  3.6  3.7  3.2  3.3  3.4]
 [ 1.4  1.5  1.6  4.4  4.5  4.6  4.1  4.2  4.3  3.8  3.9  4. ]
 [ 1.7  1.8  1.9  4.7  4.8  4.9  4.7  4.8  4.9  4.4  4.5  4.6]]
2.7013292476222723


'\ndef foo(M, W):\n    m = M.shape[0]\n    X = np.hstack([M[:m//2], M[m//2:], M[1::2], M[::2]])  \n    Y = sigmoid(X @ W)  \n    return np.sum(Y.mean(axis=0))\n'

In [ ]:
(m, n) = M.shape
m

20

In [1]:
from scipy.stats import binom

n = 35  # number of users
p = 0.10  # probability that a user is active

# Calculate the probability that 10 or fewer users are active
cumulative_prob = binom.cdf(10, n, p)

# Calculate the probability that more than 10 users are active
prob_more_than_10 = 1 - cumulative_prob

print(prob_more_than_10)

0.0004242975954508177
